GET http://localhost:5000/api/v1/user/fdfdfdf

###
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "email": "admin3@gmail.com",
    "password": "123456"
}

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin2@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJhZG1pbjJAZ21haWwuY29tIiwicm9sZV9jb2RlIjoiUjIiLCJpYXQiOjE3MjE1NTEwNzgsImV4cCI6MTcyMTk4MzA3OH0.VYBqj0aEi4XKQ8WV1r4KmWgUkewBVhAglJPfxP14prs
